/**
 * ORIGINAL PLANS – HARDCODED BACKUP
 *
 * This file contains the ORIGINAL, IMMUTABLE pricing and limit values.
 * These values serve as the MASTER TEMPLATE that can NEVER be deleted or modified.
 *
 * ⚠️ DO NOT EDIT THIS FILE – it's the permanent fallback and source of truth.
 *
 * Last updated: 2026-07-26
 */

export interface OriginalPlan {
  id: 'free' | 'creator' | 'pro';
  name: string;
  // Prices in smallest currency units (cents/haléře)
  priceCzk: number; // haléře (19900 = 199 Kč)
  priceEur: number; // cents (800 = 8 EUR)
  priceUsd: number; // cents (900 = 9 USD)
  // Limits
  maxAccounts: number; // -1 means unlimited (∞)
  maxPostsPerMonth: number; // -1 means unlimited (∞)
  aiCredits: number;
  twitterCredits: number;
}

/**
 * MASTER TEMPLATES – Original pricing plans (Postio v1.0)
 *
 * These are the ORIGINAL values from the initial launch.
 * They are stored in the database with is_master_template = true
 * and serve as the permanent fallback via "Reset to Base" button.
 */
export const ORIGINAL_PLANS: OriginalPlan[] = [
  {
    id: 'free',
    name: 'Free',
    priceCzk: 0,
    priceEur: 0,
    priceUsd: 0,
    maxAccounts: 1,
    maxPostsPerMonth: 10,
    aiCredits: 0,
    twitterCredits: 0,
  },
  {
    id: 'creator',
    name: 'Creator',
    priceCzk: 19900, // 199 Kč
    priceEur: 800, // 8 EUR
    priceUsd: 900, // 9 USD
    maxAccounts: 5,
    maxPostsPerMonth: -1, // unlimited
    aiCredits: 10,
    twitterCredits: 10,
  },
  {
    id: 'pro',
    name: 'Pro',
    priceCzk: 49900, // 499 Kč
    priceEur: 2000, // 20 EUR
    priceUsd: 2200, // 22 USD
    maxAccounts: -1, // unlimited
    maxPostsPerMonth: -1, // unlimited
    aiCredits: 50,
    twitterCredits: 50,
  },
];

/**
 * Helper to get a single plan by ID
 */
export function getOriginalPlanById(id: 'free' | 'creator' | 'pro'): OriginalPlan | undefined {
  return ORIGINAL_PLANS.find((plan) => plan.id === id);
}

/**
 * Helper to format price for display
 */
export function formatPrice(
  amount: number,
  currency: 'czk' | 'eur' | 'usd'
): string {
  if (amount === 0) return '0';

  const value = amount / 100; // Convert from cents to main unit

  switch (currency) {
    case 'czk':
      return `${value} Kč`;
    case 'eur':
      return `${value} EUR`;
    case 'usd':
      return `$${value}`;
  }
}
